#!/usr/bin/env bash
# Usage:
#   ./run_ae_clean.sh                 # DRY-RUN: list what would be deleted
#   ./run_ae_clean.sh --force         # actually delete tier-1 (cheap) outputs
#   ./run_ae_clean.sh --deep          # DRY-RUN incl. tier-2 (bitstreams/board)
#   ./run_ae_clean.sh --deep --force  # actually delete tier-1 + tier-2
#   ./run_ae_clean.sh --help
#
# NEVER deleted (inputs / references):
#   *_provided.*  *.saif  ExSpike_Top.edf/.vm  HW/netlist/*  SIM/*  source
#
# Tier 1 (cheap, regenerated by run_ae_figures / run_ae_power / xsim / cycle):
#   Artifacts/Figure*.png, Artifacts/table2.csv
#   cycle_model/results/<bench>.json   (keeps *_provided.json)
#   cycle_model/<bench>/latency_report_group_*.txt (keeps *_provided.txt)
#   cycle_model/logs/*, cycle_model/**/__pycache__
#   xsim/run/*, xsim/logs/*, xsim stray logs
#   Power_estimation/Netlist/<b>/power.txt, Power_estimation/logs/*
#
# Tier 2 (--deep; EXPENSIVE or needs FPGA board to regenerate):
#   HW/output/*.bit, *.dcp, *.rpt   (re-impl: hours each)
#   HW/logs/*
#   Log/*.log, Log/*.out, Log/vivado*, Log/.Xil   (need board re-run)
# =====================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/../sourceme"

FORCE=0
DEEP=0
for a in "$@"; do
    case "$a" in
        --force) FORCE=1 ;;
        --deep)  DEEP=1 ;;
        -h|--help) sed -n '2,27p' "$0"; exit 0 ;;
        *) echo "ERROR: unknown argument '$a'"; sed -n '2,27p' "$0"; exit 1 ;;
    esac
done

TARGETS=()   # files / dirs slated for deletion

add_glob() {
    local g
    for g in "$@"; do
        if [[ -e "$g" && "$g" != *_provided.* ]]; then TARGETS+=("$g"); fi
    done
    return 0
}

# --- Tier 1: cheap regenerable outputs ---------------------------------

# Figures + comparison table
add_glob "$ARTIFACTS"/Figure*.png
add_glob "$ARTIFACTS"/table2.csv
add_glob "$ARTIFACTS"/table1.csv

# cycle-model JSON: delete only those that have a *_provided.json sibling
if [[ -d "$CYCLE_MODEL/results" ]]; then
    for prov in "$CYCLE_MODEL"/results/*_provided.json; do
        [[ -e "$prov" ]] || continue
        gen="${prov/_provided.json/.json}"
        if [[ -f "$gen" ]]; then TARGETS+=("$gen"); fi
    done
fi

# cycle-model logs + pycache
add_glob "$CYCLE_MODEL"/logs/*.log
while IFS= read -r d; do TARGETS+=("$d"); done \
    < <(find "$CYCLE_MODEL" -type d -name __pycache__ 2>/dev/null)

# Reports under cycle_model (latency_report_*, figure8_*): delete only the
# generated file when a *_provided.txt sibling exists. Never touch *_provided.txt.
while IFS= read -r prov; do
    gen="${prov/_provided.txt/.txt}"
    if [[ -f "$gen" ]]; then TARGETS+=("$gen"); fi
done < <(find "$CYCLE_MODEL" -type f -name '*_provided.txt' 2>/dev/null)

# xsim run dirs + logs + stray artifacts
add_glob "$XSIM_DIR"/run/*
add_glob "$XSIM_DIR"/logs/*
add_glob "$XSIM_DIR"/xelab.log "$XSIM_DIR"/xvlog.log \
         "$XSIM_DIR"/xelab.pb "$XSIM_DIR"/xvlog.pb "$XSIM_DIR"/.Xil

# Power reports + post-synth util reports (keep power_provided.txt +
# the .saif/.edf/.vm inputs)
add_glob "$POWER"/Netlist/*/power.txt
add_glob "$POWER"/Netlist/*/util_hier.rpt
add_glob "$POWER"/logs/*

T1_COUNT=${#TARGETS[@]}

# --- Tier 2: expensive / hardware-dependent ----------------------------
if [[ "$DEEP" -eq 1 ]]; then
    add_glob "$OUTPUT_DIR"/*.bit "$OUTPUT_DIR"/*.dcp "$OUTPUT_DIR"/*.rpt
    add_glob "$HW_LOG_DIR"/*
    add_glob "$ROOT_DIR"/Log/*.log "$ROOT_DIR"/Log/*.out \
             "$ROOT_DIR"/Log/vivado* "$ROOT_DIR"/Log/.Xil
fi

# --- report -----------------------------------------------------------
total_bytes=0
human() { numfmt --to=iec --suffix=B "${1:-0}" 2>/dev/null || echo "${1}B"; }

print_list() {
    local t sz
    for t in "${TARGETS[@]}"; do
        sz=$(du -sb "$t" 2>/dev/null | cut -f1 || echo 0)
        total_bytes=$((total_bytes + sz))
        printf "  %10s  %s\n" "$(human "$sz")" "$t"
    done
}

echo "=============================================================="
echo " FPL_AE clean  (deep=$DEEP, force=$FORCE)"
echo "=============================================================="
if [[ ${#TARGETS[@]} -eq 0 ]]; then
    echo "Nothing to delete (already clean)."
    exit 0
fi

echo "Tier 1 (cheap, auto-regenerated): $T1_COUNT item(s)"
if [[ "$DEEP" -eq 1 ]]; then
    echo "Tier 2 (--deep, expensive/board): $(( ${#TARGETS[@]} - T1_COUNT )) item(s)"
fi
echo "--------------------------------------------------------------"
print_list
echo "--------------------------------------------------------------"
echo " Total: ${#TARGETS[@]} item(s), ~$(human "$total_bytes")"
echo "=============================================================="

if [[ "$FORCE" -eq 0 ]]; then
    echo "DRY-RUN: nothing deleted. Re-run with --force to delete."
    [[ "$DEEP" -eq 0 ]] && echo "Add --deep to also clean bitstreams / impl reports / board logs."
    exit 0
fi

for t in "${TARGETS[@]}"; do
    rm -rf "$t"
done
echo "Deleted ${#TARGETS[@]} item(s)."
