// RTL design sources for tb_top xsim (paths relative to $RTL)
aim_range_generate.v
axi_ddr/index2abs_sub.v
axi_ddr/input_uart_r.v
axi_ddr/reco_uart_send.v
axi_ddr/uart_combine_controller.v
ddr_read_ctrl_opt.v
elastic_fifo.v
event_processor_top.v
fast_filter.v
fc_core.v
fc_neuron.v
fetcher_decoder.v
fifo.v
generate_vld_final.v
layer_ctrl.v
mp_acc.v
mp_biass_acc.v
neural_proc.v
read_membrane_p.v
read_mp_bias.v
reco_compare.v
sparse_processing.v
spike_sim.v
top_fast_filter.v
weight_acc.v
weight_top.v
tb/tb_top.v
tb/ddr_model_256bit.v
